<br /><br />
<script>
	$( document ).ready(function() {
		setInterval(poll, 45000);
		function poll() {
			location.reload();
		}
	});

</script>


<div id="view-content">
	<div class="container">
		<div class="row z-depth-1"><div class="col s9 push-s3"><h2 class="green-text">SaferPlace Dashboard</h2></div></div>
		<div class="row">
			<br>
			
			<!-- barra laterale degli edifici -->
			<div class="col l3">
				<h4 class="green-text text-darken-3"><i class="small material-icons">business</i>Edifici</h4>
				<div class="fixed left-align">
					<ul class="collapsible">
						<?php
						$i=0;

						foreach ($this->edifici_e_piani as $x=>$y){

						echo "<li>";
						echo "<div class=\"collapsible-header green-text\"><b>$x</b>";
						echo '<div class="right">'.$this->persedificio[$i];
						echo "</div></div>";
						echo "<div class=\"collapsible-body\">";
						echo "<ul class=\"collection\">";
						$i++; // serve da contatore per l'indice dell'array delle persone negli edifici
						foreach ($y as $item){
						?>

						<a class="grey-text" href=

						      <?php
						   echo '"' . $this->url(
								   array(
									   'controller' => 'livello2',
									   'action' => 'dashboard',
									   'edificio' => $x,
									   'piano' => $item
								   )
							   ) . '">'.'<li class="collection-item">'.'Piano ' . $item .'</li></a>';
						   } ?>

						   <?php echo '</ul></div></li>';
					   }
						?>

					</ul>
				</div>

				<!-- barra Emergenze -->


						<h4 class="green-text text-darken-3"><i class="small material-icons">warning</i>Evacuazioni</h4>
						<div class="fixed left-align">
							<ul class="collapsible">
								<?php
								if (count($this->evacuazioni)) {
									foreach ($this->evacuazioni as $item) {

										echo "<li>";
										echo "<div class=\"collapsible-header green-text\"><b>$item->edificio Piano $item->numeroPiano</b></div>";
										echo "<div class=\"collapsible-body\">";
										echo "<ul class=\"collection\">";
										echo '<li class="collection-item grey-text">';

										switch ($item->nome) {

											case 'Allagamento':
												echo '<i class="blue-text">' . $item->nome . '</i>';
												break;

											case 'Incendio':
												echo '<i class="red-text">' . $item->nome . '</i>';
												break;

											case 'Gas':
												echo '<i class="purple-text">' . $item->nome . '</i>';
												break;

											case 'Crollo':
												echo '<i class="brown-text">' . $item->nome . '</i>';
												break;

										};

										echo '<div><a class="orange-text right"href="' . $this->url(array('controller' => 'livello2',
												'action' => 'interrupt',
												'interrupt' => $item->id)) . '
																									">
												Interrompi</a>
												 </div><br>';
										echo '</li>
											</div>';
									}
								}

								else
										echo '<p class="grey-text center"><b><br>Non sono in corso procedure di evacuazione.<br><br></b></p>';
								?>

							</ul>

						</div>




				</div>

			<!-- pianta del piano selezionato -->
			<div class="col l5">
				<?php $pianta = "image/piante/".$this->pianta; ?>

					<div class="row">

								<?php

								if (isset($this->pianta)) {
									echo '<img class="materialboxed" src="'.$this->baseUrl($pianta).'" width="100%"></img>';
								}
								else
									echo '<h5 class="grey-text center"><br><br>Seleziona un piano<br> per ottenere 
										      informazioni su di esso.</h5>';
								?>

					</div >
					<!-- informazioni su piano ed eficio selezionati -->
					<div class="row">

						<?php if (isset($this->perspiano)) {
							echo '
						<ul class="collapsible">
							<li>
								<div class="collapsible-header green-text">Persone su questo
									piano:&nbsp
									<div class="right">';
								echo $this->perspiano->numPersone.
									'</div>';

	
										?>
								</div>
							</li>
							<li>
								<div class="collapsible-header green-text">Persone per stanza:&nbsp
								</div><div class="collapsible-body">
							<?php
									foreach ($this->persperstanza as $item) {
										echo '<div class="collection-item grey-text"><b>';
										echo 	'&nbsp Stanza '. $item->stanza .
													'<div class="right">' . $item->personeStanza .'</b></div>';
										echo '</div>';
									}
								//echo '</div>';

							?>
								</div>
							</li>
							<li>
								<div class="collapsible-header green-text">Segnalazioni per stanza:&nbsp
								</div><div class="collapsible-body">
									<?php
									foreach ($this->segnalazionistanze as $item) {
										echo '<div class="collection-item grey-text"><b>';
										echo 	'&nbsp Stanza '. $item->stanza .
											'<div class="right">' . $item->segnalazionitanza .'</b></div>';
										echo '</div>';
									}
									echo '</div>';
									}
									?>
								</div>
							</li>

						</ul>

						<?php
						if((isset($this->edificio)) && (isset($this->piano))){
							echo '<div class="row"><div class="col s12 center">';
								echo '<a class="btn green white-text center" 
										href="'.$this->url(array('controller'=>'livello2',
																	 'action'=>'gestionepdf',
																	 'edificio'=>$this->edificio,
																	 'piano'=>$this->piano)).'">
									      Gestisci piani di fuga		 
									  </a>';

							echo '</div></div>';
						}?>

				</div>



			<!-- notifiche -->
			<div class="col l4">
				<h4 class="green-text text-darken-3">Notifiche<i class="small material-icons">sms_failed</i></h4>
				<!-- sezione scrollabile -->
				<div class="z-depth-1 " style="overflow-y: scroll; height: 575px;">
					<div class="container">
							<?php

							if (count($this->notifiche)){
								foreach ($this->notifiche as $item) {
									echo '<p>';
									echo '	<div class="card-content ">';
									echo '	<span class="card-title">
											<div class="chip green darken-1 white-text">'.$item->utente.'</div>
										</span>';
									echo '<ul>
										<li>Tipo: ';

									switch ($item->tipo) {

										case 'Allagamento':
											echo '<i class="blue-text">'.$item->tipo.'</i>';
											break;

										case 'Incendio':
											echo '<i class="red-text">'.$item->tipo.'</i>';
											break;

										case 'Gas':
											echo '<i class="purple-text">'.$item->tipo.'</i>';
											break;

										case 'Crollo':
											echo '<i class="brown-text">'.$item->tipo.'</i>';
											break;

									};

									echo ' <br>Edificio:  <b>'.$item->edificio.'</b>';
									echo '</li>';
									echo '	<li>
													Piano:<b>'.$item->numPiano.'</b>
																		</li>
																		<li>
													Stanza:<b>'.$item->stanza.'</b>
																		</li>
																	</ul>
										
															</div>
																<div class="card-action">
																	<a href="'.
						   														 $this->url(
																					   array(
																						   'controller' => 'livello2',
																						   'action' => 'dashboard',
																						   'edificio' => $item->edificio,
																						   'piano' => $item->numPiano)
																						    )
																						.
																'" class="green-text">Apri la mappa</a>';

									echo							'<a href="'.$this->url(
																						array(
																							'controller' => 'livello2',
																							'action' => 'delnotif',
																							'id' => $item->id,
																						)
																						). '" class="red-text"> &nbsp &nbsp Ignora</a>';
									echo '<a class="orange-text" href="'. $this->url(array(
																					'controller' => 'livello2',
																					'action'     => 'evacuazione',
																					'tipo'		 => $item->tipo,
																					'edificio'   => $item->edificio,
																					'piano'      => $item->numPiano,
																					'pos'        => $item->posizione));
									echo  '"> &nbsp &nbsp Conferma</a></div>';
									echo '</li></p><div class="divider"></div> ';

						   		}


							}
							else
								echo '<p class="grey-text center"><b>Attualmente non ci sono notifiche</b></p>';


							?>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
