<br /><br />
<div class="container">
    <!--$.ajax({
    type : 'POST',
    url : actionUrl,
    data : $("#" + formName).serialize(),
    dataType : 'json',
    success : pianiPopulate
    });-->
    <script>


        $(function(){  $("#edificio").on("change", function(){
            $("dd#piano-element").find("ul").append('<li><span>Piano 4</span></li>') ;
            $("dd#piano-element").find("select").append('<option value="4">Piano 4</option>');
            $('select').material_select();






            });

        function piani(){
            $("select#piano").append("<option>", {

                value: 1,
                text: "pirirpiri"


            });

        }


        });



    </script>

    <?

    echo $this->evacuazioneform;
?>
</div>
