<br /><br />
<div class="container">

    <script type="text/javascript">
        $(function () {
            evacuazione();
        });

        function getPiano() {
           return <?php echo "\"".$this->piano."\""; ?> ;
        }
        function ajaxEdificio (){
           return '<?php echo $this->url(array(
                                               'controller' => 'livello2',
                                               'action'     => 'ajaxedif')
                                        ); ?>';

        }
        function ajaxPianoUrl (){
            return '<?php echo $this->url(array(
                                        'controller' => 'livello2',
                                        'action'     => 'ajaxpiano')
                                         ); ?>' ;
        }

    </script>

<h4 class="green-text center"><br>Procedura di evacuazione<br><br></h4>
<?php

    echo $this->evacuazioneform;
?>
</div>
