<br /><br />
<script>
    $("document").ready(function(){removebuttons()});
</script>
<div class="container">
<div class="z-depth-1 center grey-text"><h4><br><br><i>Al momento non gestisci alcun edificio.</i><br><br><br></h4></div>
<div class="row"><div class="col s12 center"><br><br>
    <a href="<?php echo $this->url(array('controller'=>'index','action'=>'logout'))?>" class="btn-large red center">
        <b>Logout</b>
    </a>
</div></div>
</div>
