<br /><br />

<?php

//estraggo l'insieme degli edifici con i relativi piani  e li inserisco nella barra laterale
/*foreach ($this->nomiEdifici as $item){

	$nomeEdificio = $item->nome;
	echo "$nomeEdificio: ";

	$pianiEdificio = $this->edifici[$nomeEdificio];
	
	foreach ($pianiEdificio as $piani){
		echo "$piani->nome ";
	}
	echo "\n";
};*/

print_r($this->nomiEdifici);
echo "<br> <br>";
print_r($this->edifici);
?>

<div id="view-content">
	<div class="container">
		<div class="row">

			<!-- barra laterale degli edifici (DINAMICA) -->
			<div class="col s2" style="margin-top: 10%">
				<h4 class="green-text text-darken-3"><i class="small material-icons">business</i>Edifici</h4>
				<div class="fixed left-align">
					<ul class="collapsible">
						

						
					</ul>

			<!-- barra laterale degli edifici -->
					
					<!--
			<div class="col s2" style="margin-top: 10%">
				<h4 class="green-text text-darken-3"><i class="small material-icons">business</i>Edifici</h4>
				<div class="fixed left-align">
					<ul class="collapsible">
						<li>
							<div class="collapsible-header green-text"><b>Ospedale di Torrette</b></div>
							<div class="collapsible-body">
								<ul class="collection">
									<li class="collection-item grey-text">Piano 1</li>
									<li class="collection-item grey-text">Piano 2</li>
									<li class="collection-item grey-text">Piano 3</li>
									<li class="collection-item grey-text">Piano 4</li>

								</ul>
							</div>
						</li>
						<li>
							<div class="collapsible-header green-text"><b>Uffici Nexos</b></div>
							<div class="collapsible-body">
								<ul class="collection">
									<li class="collection-item grey-text">Piano 1</li>
									<li class="collection-item grey-text">Piano 2</li>
								</ul>
							</div>

						</li>
						<li>
							<div class="collapsible-header green-text"><b>Uffici Lutor Corp</b></div>
							<div class="collapsible-body">
								<ul class="collection">
									<li class="collection-item grey-text">Piano 1</li>
									<li class="collection-item grey-text">Piano 2</li>
									<li class="collection-item grey-text">Piano 3</li>
								</ul>
							</div>
						</li>
						<li>
							<div class="collapsible-header green-text"><b>Liceo Classico</b></div>
							<div class="collapsible-body">
								<ul class="collection">
									<li class="collection-item grey-text">Piano 1</li>
									<li class="collection-item grey-text">Piano 2</li>

								</ul>

							</div>
						</li>
						<li>
							<div class="collapsible-header green-text"><b>Ospedale Bellaria</b></div>
							<div class="collapsible-body">
								<ul class="collection">
									<li class="collection-item grey-text">Piano 1</li>
									<li class="collection-item grey-text">Piano 2</li>
									<li class="collection-item grey-text">Piano 3</li>
									<li class="collection-item grey-text">Piano 4</li>
								</ul>
							</div>
						</li>
					</ul>

				</div>
			</div>
			-->
				</div>	
			</div>
		</div>
	</div>

</div>