<br /><br />
<div id="view-content">
	<div class="container">

		<h3 class="center green-text">Nuova Faq</h3>

		<div class="row">
			<div class="col s8 push-s2">
				<div class="card grey lighten-5">
					<div class="card-content container">
						<?php echo $this->creafaqform; ?>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- MENU -->
	<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large blue darken-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Indietro" href="<?php echo $this->url(
			array(
				'controller' => 'livello3',
				'action' => 'gestionefaq'
			),null,true
		);

		?>">
			<i class="material-icons">arrow_back</i>
		</a>
	</div>
</div>