<br /><br />

<div id="view-content">
	<div class="container">
		<h3 class="green-text center">Gestione Faq</h3>

		<div>
			<ul class="collapsible popout" data-collapsible="accordion">
				<?php
				foreach ($this->faqSet as $faq){
					echo '<li>';
					echo '<div class="collapsible-header grey lighten-5">
							<i class="material-icons green-text">live_help</i>'. $faq->domanda .
						'</div>';
					echo '<div class="collapsible-body grey lighten-5">'.
						'<p>'.$faq->risposta.'</p>'.
						'<p>
						<a class="btn-floating btn-large green white-text tooltipped" data-position="left" data-delay="50" data-tooltip="Modifica" 
						href="';
					echo $this->url(
						array(
							'controller'=> 'livello3',
							'action' 	=> 'modificafaq',
							'domanda' 	=> $faq->domanda ,
							'risposta' 	=> $faq->risposta,
							'id' 		=> $faq->id
						));
					echo '"><i class="material-icons">edit</i></a></p>';
					echo '</div>';
				}
				?>

			</ul>
		</div>
		<div class="center-align">
			<a class="btn-floating btn-large green z-depth-1 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Aggiungi una FAQ" href="

				<?php
					echo $this->url(
						array(
							'controller'=> 'livello3',
							'action' 	=> 'creafaq',
						));
				?>

				" ><i class="material-icons">add</i>
			</a>
		</div>
	</div>
	</div>


<!-- MENU -->
<div class="fixed-action-btn vertical click-to-toggle" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red" href="#">
		<i class="material-icons">menu</i>
	</a>
	<ul>
		<li>
			<a class="btn-floating purple lighten-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Logout" href="<?php echo $this->url(
				array(
					'controller' => 'index',
					'action' => 'index'
				),null,true
			);

			?>">
				<i class="material-icons">exit_to_app</i>
			</a>
		</li>

		<li>
			<a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Edifici" href="<?php echo $this->url(
				array(
					'controller' => 'livello3',
					'action' => 'gestioneedifici'
				),null,true
			);  ?>">
				<i class="material-icons">business</i>
			</a>
		</li>

		<!--
        <li>
            <a class="btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Piani di Fuga" href="<?php echo $this->url(
			array(
				'controller' => 'livello3',
				'action' => 'gestionepianifuga'
			),null,true
		);  ?>">
                <i class="material-icons">trending_up</i>
            </a>
        </li>

        -->
		<li>
			<a class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Utenti" href="<?php echo $this->url(
				array(
					'controller' => 'livello3',
					'action' => 'gestioneutenti'
				),null,true
			);  ?>">
				<i class="material-icons">person</i>
			</a>
		</li>
		<li>
			<a class="btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Faq" href="<?php echo $this->url(
				array(
					'controller' => 'livello3',
					'action' => 'gestionefaq'
				),null,true
			);  ?>">
				<i class="material-icons">live_help</i>
			</a>
		</li>
	</ul>

</div>
</div>