<br /><br />
<div id="view-content">

	<div class="container">
		<h3 class="green-text center">Gestione Utenti</h3>

		<!-- creazione nuovo user -->
		<div class="row center">
			<div style="margin-top: 30px;">
				<a href="

					<?php
					echo $this->url(
						array(
							'controller'=> 'livello3',
							'action' 	=> 'creautente',
						),null,true);
					?>

				" class="modal-trigger waves-effect waves-light btn green">
					<i class="material-icons left">add</i>Crea utente
				</a>
			</div>
		</div>


		<!-- tabella risultati -->
		<table style="margin-top: 30px;" class="striped responsive-table">
			<thead>
			<tr>
				<th data-field="username">Username</th>
				<th data-field="nome">Nome</th>
				<th data-field="cognome">Cognome</th>
				<th data-field="email">Email</th>
				<th data-field="password">Password</th>
				<th data-field="livello">Livello</th>
				<th data-field="operazione">Operazione</th>
			</tr>
			</thead>

			<tbody>

			<?php
			foreach ($this->arrayUtenti as $utente){
				echo "<tr>";

				if(($utente->livello > 1)){
					echo "	<td class='yellow-text text-darken-3'>$utente->username</td>";
				}else{
					echo "	<td>$utente->username</td>";
				}

				echo "	<td>$utente->nome</td>";
				echo "	<td>$utente->cognome</td>";
				echo "	<td>$utente->email</td>";
				echo "	<td>$utente->password</td>";
				if(($utente->livello > 1)){
					echo "	<td>Staff</td>";
				}else{
					echo "	<td>Utente Semplice</td>";
				}
				echo "	<td>";

				//BOTTONE MODIFICA

				echo " <a class=\"btn-floating btn-flat btn-small waves-effect waves-light green white-text \" href=\"";

						// con questa ancora richiamo l'azione per MODIFICARE un utente

						echo $this->url(
							array(
								'controller'	=> 'livello3',
								'action' 		=> 'modificautente',
								'nome'			=> $utente->nome,
								'cognome' 		=> $utente->cognome,
								'genere'    	=> $utente->genere,
								'eta'       	=> $utente->eta,
								'telefono'  	=> $utente->telefono,
								'username'  	=> $utente->username,
								'password'  	=> $utente->password,
								'email'     	=> $utente->email,
								'livello'		=> $utente->livello
							));


				echo"\">
								<i class=\"material-icons\" title='Modifica Utente'>edit</i></a>
							</a>";

				//BOTTONE ASSEGNA EDIFICIO

				if(($utente->livello > 1)){
					echo "<a class=\"btn-floating btn-flat btn-small waves-effect waves-light green white-text \" href=\"";

						// con questa ancora richiamo l'azione per assegnare un edificio ad un Utente

						echo $this->url(
							array(
								'controller'	=> 'livello3',
								'action' 		=> 'scegliedificio',
								'username'  	=> $utente->username,
							));


				echo"\">
								<i class=\"material-icons\" title='Assegna Edificio'>business</i></a>
							</a>";


				}



				echo "	</td>";
				echo "</tr>";
			}
			?>

			</tbody>
		</table>

	</div>


	<!-- MENU -->
	<div class="fixed-action-btn vertical click-to-toggle" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large red" href="#">
			<i class="material-icons">menu</i>
		</a>
		<ul>
			<li>
				<a class="btn-floating purple lighten-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Logout" href="<?php echo $this->url(
					array(
						'controller' => 'index',
						'action' => 'index'
					),null,true
				);

				?>">
					<i class="material-icons">exit_to_app</i>
				</a>
			</li>

			<li>
				<a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Edifici" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestioneedifici'
					),null,true
				);  ?>">
					<i class="material-icons">business</i>
				</a>
			</li>

			<!--
        <li>
            <a class="btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Piani di Fuga" href="<?php echo $this->url(
				array(
					'controller' => 'livello3',
					'action' => 'gestionepianifuga'
				),null,true
			);  ?>">
                <i class="material-icons">trending_up</i>
            </a>
        </li>

        -->
			<li>
				<a class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Utenti" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestioneutenti'
					),null,true
				);  ?>">
					<i class="material-icons">person</i>
				</a>
			</li>
			<li>
				<a class="btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Faq" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestionefaq'
					),null,true
				);  ?>">
					<i class="material-icons">live_help</i>
				</a>
			</li>
		</ul>

	</div>
</div>