<br /><br />
<div id="view-content">
	
	
	<!-- container della pagina -->
	<div class="container">

		<h3 class="center green-text">Gestione edifici</h3>

		<p class="center">
			<a class="btn-floating btn-large red tooltipped" href="
				<?php echo $this->url(
				array(
					'controller' => 'livello3',
					'action' => 'inserisciedificio',
				),null,true
			); ?>
			"
			   data-position="left" data-delay="50" data-tooltip="Aggiungi un nuovo edificio">
				<i class="material-icons">add</i>
			</a>
		</p>

		<div class="row">

			<?php
			foreach($this->arrayEdifici as $edificio):
				$mappa="image/edifici/".$edificio['mappa'];
				?>
				<!-- card edificio -->
				<div class="col s12 m6 l4">
					<div class="card large">
						<div class="card-image waves-effect waves-block waves-light">
							<img class="activator" src="<?php echo $this->baseUrl($mappa); ?>" >
						</div>
						<div class="card-content">
							<span class="card-title activator grey-text text-darken-4"><?php echo $edificio['nome'];?><i class="material-icons right">more_vert</i></span>
							<p><a class="btn red white-text "  href="<?php echo $this->url(
									array(
										'controller' => 'livello3',
										'action' => 'modificaedificio',
										'edificio'=>$edificio['nome']
									),null,true
								); ?>">Gestisci</a></p>
						</div>
						<div class="card-reveal">
							<span class="card-title green-text "><?php echo $edificio['nome'];?><i class="material-icons right">close</i></span>
							<p><?php echo $edificio['informazioni'];?></p>
						</div>
					</div>

				</div>
				<?php
			endforeach;
			?>

		</div>

	</div>


	




	<!-- MENU -->
	<div class="fixed-action-btn vertical click-to-toggle" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large red" href="#">
			<i class="material-icons">menu</i>
		</a>
		<ul>

			<li>
				<a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Edifici" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestioneedifici'
					),null,true
				);  ?>">
					<i class="material-icons">business</i>
				</a>
			</li>

			<!--
        <li>
            <a class="btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Piani di Fuga" href="<?php echo $this->url(
				array(
					'controller' => 'livello3',
					'action' => 'gestionepianifuga'
				),null,true
			);  ?>">
                <i class="material-icons">trending_up</i>
            </a>
        </li>

        -->
			<li>
				<a class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Utenti" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestioneutenti'
					),null,true
				);  ?>">
					<i class="material-icons">person</i>
				</a>
			</li>
			<li>
				<a class="btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Faq" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestionefaq'
					),null,true
				);  ?>">
					<i class="material-icons">live_help</i>
				</a>
			</li>
		</ul>

	</div>


</div>
</div>