<br /><br />
<div id="view-content">

	<div class="container">
		<h3 class="green-text center">Gestione Utenti</h3>
		<!-- Ricerca -->
		<!--

		AL MOMENTO L'ABBIAMO RIMOSSA PERCHÈ NON È ESPLICITAMENTE CITATA NELLE SPECIFICHE


		<div class="row" style="margin-top:50px;">
			<form>
				<div class="input-field col s12 m5">
					<input type="text">
					<label >Ricerca</label>
				</div>

				<div class="input-field col s12 m5">
					<select>
						<option value="" disabled selected>Seleziona criterio di ricerca</option>
						<option value="nome">Nome</option>
						<option value="cognome">Cognome</option>
						<option value="username">Username</option>
					</select>
					<label>Cerca per...</label>
				</div>

				<div class="input-field col s4 m2">
					<input type="submit" class="btn green" action="search" value="Cerca">
				</div>
			</form>
		</div>
		-->

		<!-- creazione nuovo user -->
		<div class="row center">
			<div style="margin-top: 30px;">
				<a href="

					<?php
					echo $this->url(
						array(
							'controller'=> 'livello3',
							'action' 	=> 'creautente',
						),null,true);
					?>

				" class="modal-trigger waves-effect waves-light btn green">
					<i class="material-icons left">add</i>Crea utente
				</a>
			</div>
		</div>


		<!-- tabella risultati -->
		<table style="margin-top: 30px;" class="striped responsive-table">
			<thead>
			<tr>
				<th data-field="username">Username</th>
				<th data-field="nome">Nome</th>
				<th data-field="cognome">Cognome</th>
				<th data-field="email">Email</th>
				<th data-field="password">Password</th>
				<th data-field="livello">Livello</th>
				<th data-field="operazione">Operazione</th>
			</tr>
			</thead>

			<tbody>

			<?php
			foreach ($this->arrayUtenti as $utente){
				echo "<tr>";

				if(($utente->livello > 1)){
					echo "	<td class='yellow-text text-darken-3'>$utente->username</td>";
				}else{
					echo "	<td>$utente->username</td>";
				}

				echo "	<td>$utente->nome</td>";
				echo "	<td>$utente->cognome</td>";
				echo "	<td>$utente->email</td>";
				echo "	<td>$utente->password</td>";
				if(($utente->livello > 1)){
					echo "	<td>Staff</td>";
				}else{
					echo "	<td>Utente Semplice</td>";
				}
				echo "	<td>";

				//BOTTONE MODIFICA

				echo " <a class=\"btn-floating btn-flat btn-small waves-effect waves-light green white-text \" href=\"";

						// con questa ancora richiamo l'azione per MODIFICARE un utente

						echo $this->url(
							array(
								'controller'	=> 'livello3',
								'action' 		=> 'modificautente',
								'nome'			=> $utente->nome,
								'cognome' 		=> $utente->cognome,
								'genere'    	=> $utente->genere,
								'eta'       	=> $utente->eta,
								'telefono'  	=> $utente->telefono,
								'username'  	=> $utente->username,
								'password'  	=> $utente->password,
								'email'     	=> $utente->email,
								'livello'		=> $utente->livello
							));


				echo"\">
								<i class=\"material-icons\" title='Modifica Utente'>edit</i></a>
							</a>";

				//BOTTONE ELIMINA
				/*
				echo " <a class=\"btn-floating btn-flat btn-small waves-effect waves-light green white-text\" href=\"";

						// con questa anconcora richiamo l'azione per ELIMINARE un utente

						echo $this->url(
							array(
								'controller'=> 'livello3',
								'action' 	=> 'eliminautente',
								'username'	=> $utente->username
							));

				echo"\">
								<i class=\"material-icons\">delete</i></a>
							</a>";
				*/

				//BOTTONE ASSEGNA EDIFICIO

				if(($utente->livello > 1)){
					echo "<a class=\"btn-floating btn-flat btn-small waves-effect waves-light green white-text \" href=\"";

						// con questa ancora richiamo l'azione per assegnare un edificio ad un Utente

						echo $this->url(
							array(
								'controller'	=> 'livello3',
								'action' 		=> 'scegliedificio',
								'username'  	=> $utente->username,
							));


				echo"\">
								<i class=\"material-icons\" title='Assegna Edificio'>business</i></a>
							</a>";


				}


				echo "	</td>";
				echo "</tr>";
			}
			?>

			</tbody>
		</table>

	</div>
</div>