<br /><br />
<div id="view-content">
	<p>View script for controller <b>Livello3</b> and script/action name <b>gestionepianifuga</b></p>


	<!-- MENU -->
	<div class="fixed-action-btn vertical click-to-toggle" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large red" href="#">
			<i class="material-icons">menu</i>
		</a>
		<ul>

			<li>
				<a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Edifici" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestioneedifici'
					),null,true
				);  ?>">
					<i class="material-icons">business</i>
				</a>
			</li>

			<!--
        <li>
            <a class="btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Piani di Fuga" href="<?php echo $this->url(
				array(
					'controller' => 'livello3',
					'action' => 'gestionepianifuga'
				),null,true
			);  ?>">
                <i class="material-icons">trending_up</i>
            </a>
        </li>

        -->
			<li>
				<a class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Utenti" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestioneutenti'
					),null,true
				);  ?>">
					<i class="material-icons">person</i>
				</a>
			</li>
			<li>
				<a class="btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Faq" href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestionefaq'
					),null,true
				);  ?>">
					<i class="material-icons">live_help</i>
				</a>
			</li>
		</ul>

	</div>
</div>