<br /><br />
<div id="view-content">
	
	
	<!-- container della pagina -->
	<div class="container">

		<h3 class="center green-text">Gestione edifici</h3>

		<div class="row">

			<?php
			foreach($this->arrayEdifici as $edificio):
				$mappa="image/edifici/".$edificio['mappa'];
				?>
				<!-- card edificio -->
				<div class="col s12 m6 l4">
					<div class="card large">
						<div class="card-image waves-effect waves-block waves-light">
							<img class="activator" src="<?php echo $this->baseUrl($mappa); ?>" >
						</div>
						<div class="card-content">
							<span class="card-title activator grey-text text-darken-4"><?php echo $edificio['nome'];?><i class="material-icons right">more_vert</i></span>
							<p><a class="btn red white-text "  href="<?php echo $this->url(
									array(
										'controller' => 'livello3',
										'action' => '',
										'edificio'=>$edificio['nome']
									),null,true
								); ?>">Gestisci</a></p>
						</div>
						<div class="card-reveal">
							<span class="card-title green-text "><?php echo $edificio['nome'];?><i class="material-icons right">close</i></span>
							<p><?php echo $edificio['informazioni'];?></p>
						</div>
					</div>

				</div>
				<?php
			endforeach;
			?>


			<!-- bottone per aggiungere un nuovo edificio -->
			
		</div>

	</div>




</div>
</div>