<html>
<head>
	<script> $(document).ready(function() {
			$('select').material_select();
		}); </script>

	<script>$(document).ready(function(){
			$('ul.tabs').tabs();
		});</script>

	<script>$(document).ready(function(){
			$('.collapsible').collapsible({
				accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
			});
		});</script>

</head>
<body>


	
</body>
</html>