<html>
<head>
	<script> $(document).ready(function() {
			$('select').material_select();
		}); </script>

	<script>$(document).ready(function(){
			$('ul.tabs').tabs();
		});</script>

	<script>$(document).ready(function(){
			$('.collapsible').collapsible({
				accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
			});
		});</script>

</head>
<body>

<br>
<br>
<br>
<br>

<a href="<?php echo $this->url(
	array(
		'controller' => 'livello3',
		'action' => 'gestioneutenti'
	),null,true
);  ?>">
		<div id="index-banner" class="parallax-container z-depth-5">
			<div class="section no-pad-bot">
				<div class="container">
					<br><br><br><br><br><br>
					<h1 class="left white-text light text-lighten-2">Gestisci gli Utenti</h1>
					<br><br>

				</div>
			</div>
			<div class="parallax"><img src="<?php echo $this->baseUrl('image/UsersManagement.jpg'); ?>"></div>
		</div>
</a>

<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>

<a href="<?php echo $this->url(
	array(
		'controller' => 'livello3',
		'action' => 'gestioneedifici'
	),null,true
);  ?>">
		<div id="index-banner" class="parallax-container z-depth-5">
			<div class="section no-pad-bot">
				<div class="container">
					<br><br><br><br><br><br>
						<h1 class="right white-text light text-lighten-2">Gestisci gli Edifici</h1>
					<br><br>

				</div>
			</div>
			<div class="parallax"><img src="<?php echo $this->baseUrl('image/BuildingManagement.jpg'); ?>"></div>
		</div>
	</a>



<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>

<a href="<?php echo $this->url(
	array(
		'controller' => 'livello3',
		'action' => 'gestionefaq'
	),null,true
);  ?>">
		<div id="index-banner" class="parallax-container z-depth-5">
			<div class="section no-pad-bot">
				<div class="container">
					<br><br><br><br><br><br>
							<h1 class="left white-text light text-lighten-2">Gestisci le FAQ</h1>
					<br><br>

				</div>
			</div>
			<div class="parallax"><img src="<?php echo $this->baseUrl('image/faqManagement.jpg'); ?>"></div>
		</div>
</a>


<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>


<div class="fixed-action-btn vertical click-to-toggle " style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large purple lighten-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Logout" href="<?php echo $this->url(
		array(
			'controller' => 'index',
			'action' => 'index'
		),null,true
	);

	?>">
		<i class="material-icons">exit_to_app</i>
	</a>


	
</body>
</html>