<html>
<head>
	<script> $(document).ready(function() {
			$('select').material_select();
		}); </script>

	<script>$(document).ready(function(){
			$('ul.tabs').tabs();
		});</script>

	<script>$(document).ready(function(){
			$('.collapsible').collapsible({
				accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
			});
		});</script>

</head>
<body>

<div class="row navbar-fixed white center-align" style="position: fixed; width: 100%; height: auto;">

	<div class="container">

		<div class="col l4 s12 center-align white">
			<h2 class="card-title green-text center-align">HOME</h2>
		</div>

	</div>

</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


<div class="parallax-container valign-wrapper left z-depth-2" style="width: 1300px; height: 300px; ">
	<div class="section no-pad-bot">
		<div class="container">
			<div class="row center">
				<a href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestioneutenti'
					),null,true
				);  ?>"><h3 class="header col s12 light white-text z-depth-2">Gestisci gli Utenti</h3></a>
			</div>
		</div>
	</div>
	<div class="parallax"><img src="<?php echo $this->baseUrl('image/UsersManagement.jpg'); ?>"></div>
</div>

<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>

<div class="parallax-container valign-wrapper right z-depth-2" style="width: 1300px; height: 300px; ">
	<div class="section no-pad-bot right">
		<div class="container right">
			<div class="row right">
				<a href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestioneedifici'
					),null,true
				);  ?>"><h3 class="header col s12 light white-text z-depth-2">Gestisci gli Edifici</h3></a>
			</div>
		</div>
	</div>
	<div class="parallax"><img src="<?php echo $this->baseUrl('image/BuildingManagement.jpg'); ?>"></div>
</div>

<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>


<div class="parallax-container valign-wrapper left z-depth-2" style="width: 1300px; height: 300px; ">
	<div class="section no-pad-bot">
		<div class="container">
			<div class="row center">
				<a href="<?php echo $this->url(
					array(
						'controller' => 'livello3',
						'action' => 'gestionefaq'
					),null,true
				);  ?>"><h3 class="header col s12 light white-text z-depth-2">Gestisci le FAQ</h3></a>
			</div>
		</div>
	</div>
	<div class="parallax"><img src="<?php echo $this->baseUrl('image/faqManagement.jpg'); ?>"></div>
</div>


<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>


	
</body>
</html>