<br /><br />
<div id="view-content">
	<h4 class="green-text center">Nuovo edificio</h4>
	<div class="container">
		<?php echo $this->nuovoEdificioForm; ?>
	</div>

	<!-- MENU -->
	<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large blue darken-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Indietro" href="<?php echo $this->url(
			array(
				'controller' 	=> 'livello3',
				'action' 		=> 'verificanuovoedificio',
			),null,true
		);

		?>">
			<i class="material-icons">arrow_back</i>
		</a>
	</div>
</div>

<script type="text/javascript">

	$('#mappa').wrap('<div class="file-field input-field"><div class="btn green white-text" id="mappaFileText"><span>File</span></div></div>');
	$('#mappaFileText').after('<div class="file-path-wrapper"><input tyep="text" class="file-path validate" placeholder="Scegli file"></div>');

</script>