<html>
<head>

<body>
<br /><br />
<div id="view-content">
	<div class="container">
		<h3 class="green-text center">Modifica i tuoi dati</h3>
		<div class="card grey lighten-5">
			<div class="card-content">
				<div class="container">
					<?php echo $this->modificaprofiloform; ?>
				</div>

			</div>
		</div>
	</div>
</div>
<br /><br />

<div class="fixed-action-btn click-to-toggle vertical" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Torna alla Home" href="<?php echo $this->url(
		array('controller' => 'livello3', 'action' => 'index')) ?>">
		<i class="large material-icons">home</i>
	</a>
</div>
</body>
</head>
</html>