<br /><br />
<div id="view-content">
	<div class="container">

		<h3 class="green-text center">Gestione Faq</h3>

		<div class="row">
			<div class="col s8 push-s2">
				<div class="card">
					<div class="card-content">
						<?php echo $this->faqForm; ?>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col s8 push-s2 center-align">

					<a class=" btn white-text red" href="
					<?php
						echo $this->url(
								array(
									'controller'=> 'livello3',
									'action' 	=> 'gestionefaq',
								));
					?>
					">Annulla Modifiche</a>

			</div>
		</div>




	</div>
</div>