<br /><br />
<div id="view-content">
	<div class="container">
		<h3 class="green-text center">Modifica Utente</h3>
		<div class="card grey lighten-5">
			<div class="card-content">
				<div class="container">
					<?php echo $this->form; ?>
				</div>

			</div>
		</div>

		<div class="row">


			<div class="col s8 push-s2 center-align">

				<p>
					<a class=" btn-floating btn-large white-text red tooltipped modal-trigger" data-tooltip="Elimina Utente" data-position="left" href="#eliminautente">
						<i class="material-icons">delete</i>
					</a>
				</p>

			</div>
		</div>
	</div>

	<!-- Modal elimina utente -->
	<div id="eliminautente" class="modal">
		<div class="modal-content">
			<h4 class="green-text">Attenzione!</h4>
			<p>Sei sicuro di voler eliminare questo utente?</p>
		</div>
		<div class="modal-footer">
			<a href="
		<?php
			echo $this->url(
				array(
					'controller'=> 'livello3',
					'action' 	=> 'eliminautente',
					'id'		=> $this->username
				));
			?>
		" class="modal-action modal-close waves-effect waves-green btn-flat green-text">Si</a>
			<a href="#!" class=" modal-action modal-close waves-effect waves-red btn-flat red-text">No</a>
		</div>
	</div>


	<!-- MENU -->
	<!-- MENU -->
	<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large blue darken-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Indietro" href="<?php echo $this->url(
			array(
				'controller' 	=> 'livello3',
				'action' 		=> 'gestioneutenti',
			),null,true
		);

		?>">
			<i class="material-icons">arrow_back</i>
		</a>
	</div>
</div>