<br /><br />


<div id="view-content">

	<div class="container">

			<div class="row">

				<div class="col s6 z-depth-2 push-s3 container">

					<?php
					$mappa="image/edifici/". $this->edificio['0']->mappa;
					?>


					<div class="center ">
						<h3 class="green-text"><?php echo $this->edificio[0]->nome ?></h3>
						<img class=""  src='<?php echo $this->baseUrl($mappa);?>' width="80%">
						<br>
						<br>
						<div class="divider"></div>
						<p>
							<?php
							echo $this->edificio[0]->informazioni;
							?>
						</p>
						<div class="row">
							<div class="col s6 center ">
								<a class="btn-floating btn-large green right tooltipped" href="
									<?php
										echo $this->url(
											array(
											'controller'=> 'livello3',
											'action' 	=> 'modificadescrizione',
											'edificio'	=> $this->edificio[0]->nome
												
										),null,true);
									?>

								" data-tooltip="Modifica" data-position="left"><i class="material-icons">edit</i></a>
							</div>
                            <div class="col s6 center ">
                                <a class="btn-floating btn-large red left tooltipped modal-trigger"

                                   data-tooltip="Elimina edificio" data-position="right" href="#elimina">
                                        <i class="material-icons">delete</i>

                                </a>
                            </div>

						</div>

					</div>
				</div>


			</div>




            <div class="row">
                <!-- select piano -->
                <div class="col s4 push-s4">
                    <div class="input-field">

                        <select id="selectPiano">
                            <option  disabled selected>Seleziona Piano</option>
                            <?php
                            foreach($this->piani as $piano):
                                ?>
                                <option value="<?php echo $piano->numeroPiano;?>"><a href="#piano<?php echo $piano->numeroPiano;?>">piano <?php echo $piano->numeroPiano;?></a></option>
                                <?php
                            endforeach;
                            ?>
                        </select>

                    </div>
                </div>
            </div>


			<div class="center">
				<p>
					<a class="btn-floating btn-large green white-text tooltipped"
					   data-position="left" data-delay="50" data-tooltip="Aggiungi un nuovo piano"
					href="
						<?php
						echo $this->url(
							array(
								'controller'=> 'livello3',
								'action' 	=> 'inseriscipiano',
								'edificio'  => $this->edificio[0]->nome
							));
						?>
					">
							<i class="material-icons">add</i>
					</a>
				</p>
			</div>

		<div class="row">

			<!— corpo contenente l'elenco dei piani con i relativi bozzetti delle piante —>

			<?php

			foreach ($this->piani as $piano):

			$pianta = "image/piante/".$piano->pianta;
			?>

			<div class="col s12">
				<div class="card" id="<?php echo $piano->numeroPiano ?>">

					<div class="card-content green ">
                  <span class="card-title white-text">
                        Piano <?php echo $piano->numeroPiano ?>

					  <!— elimina —>
                      <a class="btn-large btn-flat transparent right tooltipped activator " data-position="bottom" data-delay="50" data-tooltip="Elimina Piano">
                        <i class="material-icons white-text">delete</i>
                      </a>

                      <!— piani di fuga —>
                      <a class="btn-large btn-flat transparent right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Piani di Fuga"
						 href="<?php echo $this->url(
							 array(
								 'controller' => 'livello3',
								 'action'=>'gestionepianifuga',
								 'edificio' => $this->edificio[0]->nome,
								 'numeroPiano' => $piano->numeroPiano
							 )
						 ); ?>"
					  ><i class="material-icons white-text">trending_up</i></a>

                      <!— zone —>
                      <a class="btn-large btn-flat transparent right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Gestisci Zone" href="<?php echo $this->url(
						  array(
							  'controller' => 'livello3',
							  'action'=>'gestionezone',
							  'edificio' => $this->edificio[0]->nome,
							  'numeroPiano' => $piano->numeroPiano
						  )
					  ); ?>"><i class="material-icons white-text" >border_clear</i></a>

                      <!— modifica —>
                      <a class="btn-large btn-flat transparent right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Modifica"
						 href="<?php echo $this->url(
							 array(
								 'controller' => 'livello3',
								 'action'=>'modificapiano',
								 'edificio' => $this->edificio[0]->nome,
								 'numeroPiano' => $piano->numeroPiano
							 )
						 ); ?>"><i class="material-icons white-text">edit</i></a>

                  </span>
					</div>
					<!— elimina piano —>
					<div class="card-reveal ">
						<div style="margin: 15%">
							<h2 class="green-text center-align">Attenzione!</h2>
							<h5 class="center-align">Sei sicuro di voler eliminare il piano <?php echo $piano->numeroPiano?>?</h5>

							<div class="row center-align">
								<div class="col l2 push-l4 push-m4">
									<a class=" btn-large green white-text card-title" href="
                        <?php
									echo $this->url(
										array(
											'controller'=> 'livello3',
											'action'  => 'eliminapiano',
											'numeroPiano' => $piano->numeroPiano,
											'edificio'  => $this->edificio[0]->nome
										));
									?>">Si</a><br>
								</div>
								<div class="col l2 push-l4 push-m4">
									<a class="btn-large red white-text card-title activator center">No</a>
								</div>
							</div>
						</div>
					</div>

					<div class='card-image'>
						<img src="<?php echo $this->baseUrl($pianta) ?>">
					</div>
				</div>

				<?php endforeach; ?>


			</div>

			<br>


			<div class="center">

				<p>
					<a id='top'
					   onclick="scrollToTop()"
					   class="btn-floating btn-large blue darken-3 tooltipped"
					   data-position="top" data-delay="50" data-tooltip="Torna su">
						<i class="material-icons">keyboard_arrow_up</i></a>
				</p>
			</div>
	</div>


	<!-- MENU -->
	<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large blue darken-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Indietro" href="<?php echo $this->url(
			array(
				'controller' => 'livello3',
				'action' => 'gestioneedifici'
			),null,true
		);

		?>">
			<i class="material-icons">arrow_back</i>
		</a>
	</div>

</div>




<!-- Modal elimina edificio -->
<div id="elimina" class="modal">
    <div class="modal-content">
        <h4 class="green-text">Attenzione!</h4>
        <p>Sei sicuro di voler eliminare questo edificio?</p>
    </div>
    <div class="modal-footer">
        <a href="
		<?php
        echo $this->url(
            array(
                'controller'=> 'livello3',
                'action' 	=> 'eliminaedificio',
                'edificio'  => $this->edificio[0]->nome
            ));
        ?>
		" class="modal-action modal-close waves-effect waves-green btn-flat green-text">Si</a>
        <a href="#!" class=" modal-action modal-close waves-effect waves-red btn-flat red-text">No</a>
    </div>
</div>