<br /><br />
<div id="view-content">

	<div class="container">

			<div class="row">

				<div class="col s6 z-depth-2 push-s3 container">

					<?php
					$mappa="image/edifici/". $this->edificio['0']->mappa;
					?>


					<div class="center ">
						<h3 class="green-text"><?php echo $this->edificio[0]->nome ?></h3>
						<img class=""  src='<?php echo $this->baseUrl($mappa);?>' width="80%">
						<br>
						<br>
						<div class="divider"></div>
						<p>
							<?php
							echo $this->edificio[0]->informazioni;
							?>
						</p>
						<div class="row">
							<div class="col s6 center ">
								<a class="btn-floating btn-large green right tooltipped" href="
									<?php
										echo $this->url(
											array(
											'controller'=> 'livello3',
											'action' 	=> 'modificadescrizione',
											'edificio'	=> $this->edificio[0]->nome
												
										),null,true);
									?>

								" data-tooltip="Modifica" data-position="left"><i class="material-icons">edit</i></a>
							</div>
                            <div class="col s6 center ">
                                <a class="btn-floating btn-large red left tooltipped modal-trigger"

                                   data-tooltip="Elimina edificio" data-position="right" href="#elimina">
                                        <i class="material-icons">delete</i>

                                </a>
                            </div>

						</div>

					</div>
				</div>


			</div>




            <div class="row">
                <!-- select piano -->
                <div class="col s4 push-s4">
                    <div class="input-field">

                        <select id="selectPiano">
                            <option  disabled selected>Seleziona Piano</option>
                            <?php
                            foreach($this->piani as $piano):
                                ?>
                                <option value="<?php echo $piano->numeroPiano;?>"><a href="#piano<?php echo $piano->numeroPiano;?>">piano <?php echo $piano->numeroPiano;?></a></option>
                                <?php
                            endforeach;
                            ?>
                        </select>

                    </div>
                </div>
            </div>


			<div class="center">
				<p>
					<a class="btn-floating btn-large green white-text tooltipped"
					   data-position="left" data-delay="50" data-tooltip="Aggiungi un nuovo piano">
							<i class="material-icons">add</i>
					</a>
				</p>
			</div>


			<div class="row">

				<!-- corpo contenente l'elenco dei piani con i relativi bozzetti delle piante -->



						<?php

							foreach ($this->piani as $piano){

								$pianta = "image/piante/".$piano->pianta;

								echo '<div class="col s12">';
								echo "<div class='card' id='". $piano->numeroPiano ."'>";

								echo 	"<div class=\"card-content green \">";
      							echo		"<span class=\"card-title activator white-text \">
											Piano ".$piano->numeroPiano."<a class='btn-floating btn-large white right tooltipped' data-position=\"left\" data-delay=\"50\" data-tooltip=\"Modifica\"><i class=\"material-icons green-text text-darken-1 \">edit</i></a></span>";
								echo 	'</div>';

								echo 	"<div class='card-image'>";
								echo 		'<img src="'. $this->baseUrl($pianta) . '">';
								echo 	'</div>';
								echo "</div>";
							}
						?>


			</div>

			<br>


			<div class="center">

				<p>
					<a id='top'
					   onclick="scrollToTop()"
					   class="btn-floating btn-large blue darken-3 tooltipped"
					   data-position="top" data-delay="50" data-tooltip="Torna su">
						<i class="material-icons">keyboard_arrow_up</i></a>
				</p>
			</div>
	</div>


	<!-- MENU -->
	<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large blue darken-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Indietro" href="<?php echo $this->url(
			array(
				'controller' => 'livello3',
				'action' => 'gestioneedifici'
			),null,true
		);

		?>">
			<i class="material-icons">arrow_back</i>
		</a>
	</div>

</div>




<!-- Modal elimina faq -->
<div id="elimina" class="modal">
    <div class="modal-content">
        <h4 class="green-text">Attenzione!</h4>
        <p>Sei sicuro di voler eliminare questo edificio?</p>
    </div>
    <div class="modal-footer">
        <a href="
		<?php
        echo $this->url(
            array(
                'controller'=> 'livello3',
                'action' 	=> 'eliminaedificio',
                'edificio'  => $this->edificio[0]->nome
            ));
        ?>
		" class="modal-action modal-close waves-effect waves-green btn-flat green-text">Si</a>
        <a href="#!" class=" modal-action modal-close waves-effect waves-red btn-flat red-text">No</a>
    </div>
</div>