<br /><br />
<div id="view-content">
	<div class="container">

		<h3 class="green-text center">Gestione Faq</h3>

		<div class="row">
			<div class="col s8 push-s2">
				<div class="card grey lighten-5">
					<div class="card-content container">
						<?php echo $this->faqForm; ?>
					</div>
				</div>
			</div>
		</div>
		<div class="row">


			<div class="col s8 push-s2 center-align">
				<p>
					<a class=" btn-floating btn-large white-text red tooltipped modal-trigger" data-tooltip="Elimina Faq" data-position="top" href="#eliminafaq">
						<i class="material-icons">delete</i>
					</a>
				</p>
			</div>
		</div>
	</div>



	<!-- Modal elimina faq -->
	<div id="eliminafaq" class="modal">
		<div class="modal-content">
			<h4 class="green-text">Attenzione!</h4>
			<p>Sei sicuro di voler eliminare questa Faq?</p>
		</div>
		<div class="modal-footer">
			<a href="
		<?php
			echo $this->url(
				array(
					'controller'=> 'livello3',
					'action' 	=> 'eliminafaq',
					'id'		=> $this->id
				));
			?>
		" class="modal-action modal-close waves-effect waves-green btn-flat green-text">Si</a>
			<a href="#!" class=" modal-action modal-close waves-effect waves-red btn-flat red-text">No</a>
		</div>
	</div>


	<!-- MENU -->
	<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large blue darken-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Indietro" href="<?php echo $this->url(
			array(
				'controller' => 'livello3',
				'action' => 'gestionefaq'
			),null,true
		);

		?>">
			<i class="material-icons">arrow_back</i>
		</a>
	</div>
</div>