<br /><br />
<div id="view-content">
	<h4 class="green-text center">Modifica Piano <?php echo $this->numeroPiano?></h4>
	<div class="container">
		<?php echo $this->formmodificapiano; ?>
	</div>

	<!-- MENU -->
	<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large blue darken-2 tooltipped" data-position="left" data-delay="50" data-tooltip="Indietro" href="<?php echo $this->url(
			array(
				'controller' 	=> 'livello3',
				'action' 		=> 'modificaedificio',
				'edificio'		=> $this->edificio
			),null,true
		);

		?>">
			<i class="material-icons">arrow_back</i>
		</a>
	</div>
</div>