<html>
<body>
<div class="container">
	<!-- Titolo -->
	<div class="row">
		<div class="col l4 s6">
			<h3 class="green-text text-darken-2 left-align">Ospedale di Torrette Ancona</h3>
		</div>

		<!-- pulsanti -->
		<div class="col l8 s12" style="margin-top: 1%">
			<div class="input-field col s3">
				<select>
					<option value="" disabled selected>Seleziona Piano</option>
					<option value="1">piano 1</option>
					<option value="2">piano 2</option>
					<option value="3">piano 3</option>
				</select>
			</div>
			<div class="input-field col s3">
				<select>
					<option value="" disabled selected>Seleziona posizione</option>
					<option value="1">stanza 1</option>
					<option value="2">stanza 2</option>
					<option value="3">stanza 3</option>
					<option value="4">stanza 4</option>
					<option value="5">stanza 5</option>
				</select>
			</div>

			<a class="green btn" style="margin-top: 17px">vai</a>
		</div>
	</div>

	<!-- sottotitolo -->
	<div class="row" style="margin-top: -1%">
		<h6 class="black-text">Complesso ospedaliero situato nel quartiere Torrette di Ancona in Via Conca 71 - Torrette Ancona</h6>
	</div>

	<br>

	<!-- immagine 1 -->
	<div class="row">

		<h3 class="green-text text-darken-2 center-align"> Piano 1 </h3>
		<div class="col l12 s12 m12 center">
			<img src="<?php echo $this->baseUrl('image/edifici/piano-1-stanze.jpg'); ?>" style="height:80%; width: 80%">
		</div>
		<div class="col l12 s12 m12 center-align">
			<h5>informazioni sul piano</h5>
		</div>

	</div>

	<br>
	<br>
	<br>

	<!-- immagine 2 -->
	<div class="row">
		<h3 class="green-text text-darken-2 center-align"> Piano 2 </h3>

		<div class="col l12 s12 m12 center">
			<img src="<?php echo $this->baseUrl('image/edifici/piano-2-stanze.jpg'); ?>" style="height:80%; width: 80%">
		</div>
		<div class="col l12 s12 m12 center-align">
			<h5>informazioni sul piano</h5>
		</div>

	</div>
</div>


</body>

</html>
