<br /><br />
<div id="view-content">
	<div class="container">
		<div class="center-align">
			<h4 class="green-text">Faq</h4>
		</div>
		<div id="gestFAQ">
			<ul class="collapsible popout" data-collapsible="accordion">

				<!-- BLOCCHI DELLE FAQ GENERATI DINAMICAMENTE -->
				<?php
				foreach ($this->faqSet as $faq){
					echo '<li>';
					echo '<div class="collapsible-header">
								<i class="material-icons green-text">live_help</i>'. $faq->domanda .
						'</div>';
					echo '<div class="collapsible-body">'.
						'<p>'.$faq->risposta.'</p>';
					echo '</div>';
				}

				?>
			</ul>
		</div>
	</div>

	<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Torna Alla Home" href="<?php echo $this->url(
			array('controller' => 'index', 'action' => 'index'),null,true); ?>">
			<i class="large material-icons">home</i>
		</a>
	</div>
</div>

</div>