<html>
<head>
</head>
<body>

<!-- CONTAINER CON EFFETTO PARALLASSE     GET STARTED-->
<div class="container">
	<!-- Modal Accedi -->
	<div class="row">
		<br>
		<br>
		<!-- blocco di login -->
		<div class="col s12 ">

			<h5 class="green-text center-align">Accedi</h5>
			<?php echo $this->loginform; ?>

			<div class=" right-align" style="margin-top: -2%">
				Non sei registrato?
				<a href="<?php echo $this->url(
					array(
						"controller" => "index",
						"action" => "registrautente",
					)
				); ?>" class="modal-trigger" >Registrati</a>
			</div>
		</div>
	</div>

</div>
<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Torna Alla Home" href="<?php echo $this->url(
		array('controller' => 'index', 'action' => 'index'),null,true); ?>">
		<i class="large material-icons">home</i>
	</a>
</div>


</body>
</html>