<html>
<head>
</head>
<body>

<!-- CONTAINER CON EFFETTO PARALLASSE     GET STARTED-->
<div class="container">
	<!-- Modal Accedi -->
	<div class="row">
		<br>
		<br>
		<!-- blocco di login -->
		<div class="col s12 ">

			<h5 class="green-text center-align">Accedi</h5>
			<?php echo $this->loginform; ?>

			<div class=" right-align" style="margin-top: -2%">
				Non sei registrato?
				<a href="<?php echo $this->url(
					array(
						"controller" => "index",
						"action" => "registrautente",
					)
				); ?>" class="modal-trigger" >Registrati</a>
			</div>
		</div>
	</div>

</div>

</body>
</html>