<html>
<head>
	<?php
	$registra=$this->registra;
	if($registra==='registra')$nascosto='hiddendiv';
	else $nascosto='';
	
	?>
</head>
<body>

<!-- CONTAINER CON EFFETTO PARALLASSE     GET STARTED-->
<div class="container">
	<!-- Modal Accedi -->
	<div class="row">
		<br>
		<br>
			<!-- blocco di login -->
			<div class="col s12 ">

				<?php if($registra===0){
					echo '<h5 class="green-text center-align">Accedi</h5>';
					echo $this->loginform;
				      }
				 if ($registra==='registra'){
					 echo '<h5 class="green-text center-align">Registrati</h5>';
					 echo $this->registratiform;
				 }

				?>
				<div class="<?php echo $nascosto ?> right-align" style="margin-top: -2%">
					Non sei registrato?
					<a href="<?php echo $this->url(
						array(
							"controller" => "index",
							"action" => "registrautente",
							"registra"=>"registra"
						)
					); ?>" class="modal-trigger" >Registrati</a>
				</div>
			</div>
	</div>

</div>

</body>
</html>