<br /><br />
<div id="view-content">
	<div class="container">
		<div id="gestFAQ">
			<ul class="collapsible popout" data-collapsible="accordion">

				<!-- BLOCCHI DELLE FAQ GENERATI DINAMICAMENTE -->
				<?php
					foreach ($this->faqSet as $faq){
						echo '<li>';
						echo '<div class="collapsible-header"><i class="material-icons green-text">live_help</i>'.$faq->domanda . '</div>';
						echo '<div class="collapsible-body">'.
							 	'<p>'.$faq->risposta.'</p>';
						echo '<p>
							<a href="edit" class="btn-floating btn-large green white-text"><i class="material-icons">edit</i></a>
						</p></div>';
					}

				?>
				</ul>
			</div>
		</div>
	</div>
	
</div>