<html>
<body>


		<?php
		$edificio=$this->numPianoEdificio->current()->edificio;
		$piano=$this->numPianoEdificio->current()->numPiano;
		$errore=$this->errore;
		?>

	<script>

		$(document).ready(function(){
			$("area").addClass('areaim');

			$(".areaim").on('click', function(){
				var stanza = Number(this.alt) + 1 ; //voglio l' n+1esimo elemento della select, perchè il primo
													// è quello di default


				$("dd#segnalastanza-element").find("li.active").removeClass('active selected');
				$("#segnalastanza-element").find("ul li:nth-child(" +stanza +")").addClass('active selected');
				$("select#segnalastanza-element").find('option').removeAttr('selected');
				$("#segnalastanza-element").find("select#segnalastanza option:nth-child(" +stanza +")").attr('selected', 'selected');
				$('select').material_select();
			});

		});

	</script>



<!-- barra fissa con nome edificio e box per scorrere i piani-->
<div >

	<!-- Titolo -->
	<div class="row white center-align">

		<div class="container">

			<div class="col l12 s12 center-align white">
				<h3 class="green-text text-darken-2 center-align white"><?php echo $edificio.' Piano '. $piano;?></h3>
				<?php
				if($errore==='errore')
					echo '<h5 class="red-text text-darken-2 center-align white">Devi selezionare una stanza</h5>'
				?>
			</div>

		</div>

	</div>

</div>

<!--mappa e form-->
<div class="container" >
	<!-- PIANO # + immagine -->

	<?php $pianta="image/piante/".$edificio.' Piano '.$piano.'.jpg'; ?>


	<!-- imposto l'id per il riferimento al piano ad uno spazio prima di ogni piano-->
	<!--inizia l'elenco dei piani-->
	<div class="row">

		<div class="input-field col l3 m3 s3 offset-l4 " style="margin-top: -1%" >


			<?php echo $this->segnalaform; ?>

		</div>
		<div class="col l12 s12 m12 center">
			<img src="<?php echo $this->baseUrl($pianta); ?>" usemap="#piantamap" style="height:80%; width: 80%">

				<map name="piantamap" class="mappa">
					<?php
					$file = APPLICATION_PATH .'/../public/image/piante/map/'.$edificio. ' Piano '.$piano.".txt";

					if (file_exists($file)) {
						$handler = fopen($file, "r");
						echo fread($handler, filesize($file));
					}
					?>
				</map>

		</div>
	</div>

	<br>
	<br>
	<br>
</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Indietro" href="<?php echo $this->url(
		array('controller' => 'livello1', 'action' => 'segnalazione'),null,true) ?>">
		<i class="large material-icons">arrow_back </i>
	</a>
</div>

</body>
</html>
