<html>
<head>
	<div>
		<?php
		$piano=$this->u[0]['edificio'];
		$info=$this->v[0]['informazioni'];
		$option=0;
		?>
	</div>
</head>

<body>

<div class="container">

    <!-- Titolo -->
    <div class="row white pinned center-align relative" style="width: 100%">
        <div class="col l4 s6 center-align white">
            <h3 class="green-text text-darken-2 center-align"><?php echo $piano;?></h3>
            <h6 class="black-text"><?php echo $info;?></h6>
        </div>
        <!-- select piano -->
        <div class="col l8 s12" style="margin-top: 1%">
            <div class="input-field col s3">
                <select id="selectPiano">
                    <option  disabled selected>Seleziona Piano</option>
                    <?php
                    foreach($this->u as $piano):
                        ?>
                        <option value="<?php echo $piano['numeroPiano'];?>"><a href="#piano<?php echo $piano['numeroPiano'];?>">piano <?php echo $piano['numeroPiano'];?></a></option>
                        <?php
                    endforeach;
                    ?>
                </select>
            </div>
        </div>
    </div>

		<br>
		<br>


		<!-- PIANO # + immagine -->
		<?php
	//mostra tutti i piani dell'edificio selezionato
	foreach($this->u as $piano):
		$pianta="image/piante/".$piano['pianta'];
		?>
		<div class="row">

			<h3 id="<?php echo $piano['numeroPiano'];?>" class="green-text text-darken-2 center-align">Piano <?php echo $piano['numeroPiano'];?></h3>


			<div class="input-field col l3 m3 s3 offset-l4 " >

				<select id="stanza">
					<option disabled selected >Seleziona posizione</option>
					<?php
					$cont=0;
					while($cont<$piano['nstanze']):
						$cont++;
						?>
						<option  value="<?php echo $cont;?>" >stanza  <?php echo $cont;?></option>
						<?php
					endwhile;
					?>
				</select>
			</div>
			<a class="green btn center" style="margin-top: 17px" href="<?php echo $this->url(
				array(
					'controller' => 'livello1',
					'action' => 'index',
					'zona'=>'a',
					'stanza'=>'1',
					'idPiano'=>'2',
				)
			);  ?>">Posizionati  </a>


			<div class="col l12 s12 m12 center">
				<img src="<?php echo $this->baseUrl($pianta); ?>" style="height:80%; width: 80%">
			</div>
		</div>

		<br>
		<br>
		<br>
		<?php
	endforeach;
	?>
		</div>

	</div>
</body>
</html>
