<html>
<body>

		<?php
		$edificio=$this->insiemeEdifici;
		$piano=$this->insiemePiani;
		$errore=$this->errore;
		$option=0;
		?>

	<script>

		$(document).ready(function(){
			$("area").addClass('areaim');

			$(".areaim").on('click', function(){
				var stanza = Number(this.alt) + 1 ; //voglio l' n+1esimo elemento della select, perchè il primo
													// è quello di default

				$("#elencostanze-element").find('.active').removeClass('active selected');
				$("#elencostanze-element").find("ul li:nth-child(" +stanza +")").addClass('active selected');
				$("select#elencostanze").find('option').removeAttr('selected');
				$("#elencostanze-element").find("select#elencostanze option:nth-child(" +stanza +")").attr('selected', 'selected');
				$('select').material_select();
			});

		});

	</script>

	<!-- barra fissa con nome edificio e box per scorrere i piani-->
		<div>

		<!-- Titolo -->
		<div class="row white center-align">

			<div class="container">

				<div class="col l12 s12 center-align white">
					<h3 class="green-text text-darken-2 center-align white"><?php echo $edificio.' Piano '. $piano;?></h3>
					<?php
					if($errore==='errore')
					echo '<h5 class="red-text text-darken-2 center-align white">Devi selezionare una stanza</h5>'
					?>
				</div>

			</div>

		</div>

	</div>

	<!--elenco dei piani con immagini-->
	<div class="container" >
			<!-- PIANO # + immagine -->

			<?php $pianta="image/piante/".$edificio.' Piano '.$piano.'.jpg'; ?>

	
			<!-- imposto l'id per il riferimento al piano ad uno spazio prima di ogni piano-->
			<!--inizia l'elenco dei piani-->
			<div class="row">
	
				<div class="input-field col l3 m3 s3 offset-l4 " style="margin-top: -1%" >


					<?php echo $this->formstanza; ?>
					
				</div>
				<div class="col l12 s12 m12 center">
					<img id="pianta" src="<?php echo $this->baseUrl($pianta); ?>" usemap="#piantamap" style="height:80%; width: 80%">

					<map name="piantamap" class="mappa">
						<?php
								$file = APPLICATION_PATH .'/../public/image/piante/map/'.$this->insiemeEdifici. ' Piano '.$this->insiemePiani.".txt";

								if ($handler = fopen($file, "r"))
									echo fread($handler, filesize($file)); ?>
					</map>
					
				</div>
			</div>
	
			<br>
			<br>
			<br>
	</div>

	<!-- prova mappatura
	<div class="container">

		<map id="mappaprova" name="mappaprova">
			<area shape="rect" alt="stanza 1" title="1" coords="94,54,298,298" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'index', 'edificio'=> $edificio,
					'numPiano'=>$piano,
					'stanza'=>'1')) ?>"  target=""/>
			<area shape="rect" alt="stanza 2" title="2" coords="310,54,510,300" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'index', 'edificio'=> $edificio,
					'numPiano'=>$piano,
					'stanza'=>'2')) ?>" target="" />
			<area shape="rect" alt="stanza 3" title="3" coords="522,52,722,296" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'index', 'edificio'=> $edificio,
					'numPiano'=>$piano,
					'stanza'=>'3')) ?>" target="" />
			<area shape="rect" alt="stanza 4" title="4" coords="736,54,934,302" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'index', 'edificio'=> $edificio,
					'numPiano'=>$piano,
					'stanza'=>'4')) ?>" target="" />
			<area shape="rect" alt="stanza 5" title="5" coords="226,470,430,714" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'index', 'edificio'=> $edificio,
					'numPiano'=>$piano,
					'stanza'=>'5')) ?>" target="" />
			<area shape="rect" alt="stanza 6" title="6" coords="444,472,588,714" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'index', 'edificio'=> $edificio,
					'numPiano'=>$piano,
					'stanza'=>'6')) ?>" target="" />
			<area shape="rect" alt="stanza 7" title="7" coords="600,470,804,708" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'index', 'edificio'=> $edificio,
					'numPiano'=>$piano,
					'stanza'=>'7')) ?>" target="" />
		</map>
		<img alt="Esempio mappatura" src="<?php echo $this->baseUrl('image/piante/Uffici 3tech piano 1.jpg');?>" usemap="#mappaprova">
-->
	</div>


	<div class="fixed-action-btn click-to-toggle vertical" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Indietro" href="<?php echo $this->url(
			array('controller' => 'livello1', 'action' => 'checkinint', 'edificio' => $edificio),null,true); ?>">
			<i class="large material-icons">arrow_back</i>
		</a>
	</div>


</body>
</html>
