<html>
<head>
	<div>
		<?php
		$piani=$this->insiemePiani[0]['edificio'];
		$option=0;
		?>
	</div>
</head>
<body>


<!-- barra fissa con nome edificio e box per scorrere i piani-->
<div style="margin-bottom: 200px" >

	<!-- Titolo -->
	<div class="row navbar-fixed white center-align" style="position: fixed; width: 100%; height: auto;">

		<div class="container">

			<div class="col l4 s12 center-align white">
				<h3 class="green-text text-darken-2 center-align white"><?php echo $piani;?></h3>
			</div>
			<!-- select piano -->
			<div class="col l8 s12" style="margin-top: 1%;">
				<div class="input-field col s3">
					<select id="selectPiano">
						<option  disabled selected>Seleziona Piano</option>
						<?php
						foreach($this->insiemePiani as $piani):
							?>
							<option value="<?php echo $piani['numeroPiano'];?>"><a href="#piano<?php echo $piani['numeroPiano'];?>">piano <?php echo $piani['numeroPiano'];?></a></option>
							<?php
						endforeach;
						?>
					</select>
				</div>
			</div>

		</div>

	</div>

</div>



<!--elenco dei piani con immagini-->
<div class="container" >
	<!-- PIANO # + immagine -->
	<?php
	//mostra tutti i piani dell'edificio selezionato
	foreach($this->insiemePiani as $piano):
		$pianta="image/piante/".$piano['pianta'];
		?>

		<!-- imposto l'id per il riferimento al piano ad uno spazio prima di ogni piano-->
		<br id="<?php echo $piano['numeroPiano'];?>">

		<!--inizia l'elenco dei piani-->
		<div class="row">

			<h3 class="green-text text-darken-2 center-align">Piano <?php echo $piano['numeroPiano'];?></h3>

			<p class="center"><a class="green btn center" href="<?php echo $this->url(
				array(
					'controller' => 'livello1',
					'action' => 'checkinb',
					'numPiano'=> $piano['numeroPiano'],
				)
			);  ?>">Seleziona Piano</a></p>


			<div class="col l12 s12 m12 center">
				<img src="<?php echo $this->baseUrl($pianta); ?>" style="height:80%; width: 80%">
			</div>
		</div>

		<br>
		<br>
		<br>
		<?php
	endforeach;
	?>
</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red">
		<i class="large material-icons">add_circle</i>
	</a>
	<ul>
		
		<li><a class="btn-floating purple lighten-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Logout" href="<?php echo $this->url(
				array('controller' => 'index', 'action' => 'index'),null,true); ?>"><i class="material-icons">exit_to_app</i></a></li>

		<li><a class="btn-floating yellow tooltipped" data-delay="50" data-position="left" data-tooltip="Indietro" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'checkin'),null,true); ?>">
				<i class="large material-icons">replay</i>
			</a></li>

	</ul>
</div>


</body>
</html>
