<html>
<head>
<div>
<?php print_r( $this->getIdentity) ?>
	</div>
</head>
<body>


<div class="container">

	<!-- Titolo -->
	<h2 class="green-text center-align">Esegui il Check-In</h2>

	<!-- edifici -->

	<div class="row">
		<?php
		foreach($this->insiemeEdifici as $edificio):
			$mappa="image/edifici/".$edificio['mappa'];
			?>
			<!-- card edificio -->
			<div class="col s12 m6 l4">
				<div class="card large">
					<div class="card-image waves-effect waves-block waves-light">
						<img class="activator" src="<?php echo $this->baseUrl($mappa); ?>" >
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4"><?php echo $edificio['nome'];?><i class="material-icons right">more_vert</i></span>
						<p><a class="btn red white-text "  href="<?php echo $this->url(
								array(
									'controller' => 'livello1',
									'action' => 'checkinint',
									'edificio'=>$edificio['nome']
								)
							); ?>">Check-in</a></p>
					</div>
					<div class="card-reveal">
						<span class="card-title green-text "><?php echo $edificio['nome'];?><i class="material-icons right">close</i></span>
						<p><?php echo $edificio['informazioni'];?></p>
					</div>
				</div>

			</div>
			<?php
		endforeach;
		?>
	</div>

</div>

<div class="fixed-action-btn click-to-toggle vertical" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Torna alla Home" href="<?php echo $this->url(
		array('controller' => 'livello1', 'action' => 'index'),null,true); ?>">
		<i class="large material-icons">home</i>
	</a>
</div>




</body>
</html>