<html>
<html>
	<style>
		#sx{
			padding-top: 80px;
			padding-left: 5%;
			padding-right: 5%;
		}
		#dx{
			padding-top: 80px;
			padding-left: 2%;
			padding-right: 5%;

		}
	</style>
		<?php
		$edificio=$this->arrayInformazioni['edificio'];
		$numPiano=$this->arrayInformazioni['numPiano'];
		$stanza=$this->arrayInformazioni['stanza'];
		$evacuare=$this->evacuare;
		?>
	<!---->
<body>
<br>
<br>
<br>
<audio id="myAudio">
	<source src="<?php echo $this->baseUrl('suoni/allarme2.mp3');?>">
</audio>
<script>
	$( document ).ready(function() {
		setInterval(poll, 45000);
		function poll() {
			location.reload();
		}

	});
</script>
<?php if($evacuare): ?>
<script>
	$( document ).ready(function() {
			setInterval(alertFunc, 800);
		function alertFunc() {
			$( "body" ).effect("highlight",{color: 'yellow'},600);
		}
	});
	$( document ).ready(function() {
		var x = document.getElementById("myAudio");
		setInterval(alertFunc2);
		function alertFunc2() {
			x.play();
		}
	});
</script>
<?php
endif;
?>
<?php if($evacuare): ?>
	<div id="toggle" class=" row center">
		<h1 class="red-text accent-3">Pericolo sul tuo piano, mettiti in salvo </h1>
		<div class="col s12 ">
	<a href="<?php echo $this->url(
		array(
			'controller' => 'livello1',
			'action' => 'visualizzafuga',
		)
	); ?>" id="start" class="btn-large   red accent-3 modal-trigger"><b>Scappa</b></a>

		</div>
	</div>
<?php endif; ?>
		<div class="row">
			<!-- parte sinistra -->
			<div id="sx" class="col s12 m4 center">
				<div class="card grey lighten-2">
					<div class="card grey">
						<div class="card-content white-text">
							<h4><?php echo $edificio ?></h4>

							<div class="card-image"><img class="responsive-img" src="<?php echo $this->baseUrl('image/edifici/'.$edificio.'.jpg'); ?>"> </div>
							<table class="bordered">

								<tbody>
								<tr>
									<td>Piano:</td>
									<td><?php echo $numPiano;?></td>

								</tr>
								<tr>
									<td>Stanza:</td>
									<td><?php echo $stanza;?></td>
								</tr>

								</tbody>
							</table>

						</div>

					</div>

				</div>
				<a class="btn-floating btn-large red tooltipped" data-position="bottom" data-delay="50" data-tooltip="Check-out"  
				   href="<?php echo $this->url(array('controller' => 'livello1', 'action' => 'cancellaposizione'),null,true); ?>">
					<i class="material-icons">exit_to_app</i></a>

			</div>
			<!-- parte destra -->
			<div id="dx" class="col s12 m8 l8">
				<div class="center">
					<img class="responsive-img" src="<?php echo $this->baseUrl('image/piante/'.$edificio.' Piano '.$numPiano.'.jpg'); ?>" >
				</div>
			</div>
		</div>

<!--tasto menu -->
<div class="fixed-action-btn click-to-toggle vertical" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red click-to-toggle">
		<i class="large material-icons">menu</i>
	</a>
	<ul>
		<li><a class="btn-floating orange tooltipped" data-position="left" data-delay="50" data-tooltip="FAQ" href="<?php echo $this->url(
				array('controller' => 'index', 'action' => 'faq'),null,true); ?>"><i class="material-icons">live_help</i></a></li>
		<li><a class="btn-floating cyan tooltipped" data-position="left" data-delay="50" data-tooltip="Riposizionati" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'checkin'),null,true); ?>"><i class="material-icons">place</i></a></li>

		<li><a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Scappa" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'visualizzafuga'),null,true); ?>"  ><i class="material-icons">directions</i></a></li>

		<li><a class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Segnala" href="<?php echo $this->url(
		array('controller' => 'livello1', 'action' => 'segnalazione'),null,true); ?>"><i class="material-icons">add_alert</i></a></li>

	</ul>
</div>
</body>
</html>