<html>
<head>

	<style>
		#sx{
			padding-top: 80px;
			padding-left: 5%;
			padding-right: 5%;
		}
		#dx{
			padding-top: 80px;
			padding-left: 2%;
			padding-right: 5%;

		}
	</style>
	
	<div>
		<?php
		$edificio=$this->arrayInformazioni['edificio'];
		$numPiano=$this->arrayInformazioni['numPiano'];
		$stanza=$this->arrayInformazioni['stanza'];
		?>
	</div>
</head>
<body>
		<div class="row">
			<!-- parte sinistra -->
			<div id="sx" class="col s12 m4 center">
				<div class="card grey lighten-2">
					<div class="card grey">
						<div class="card-content white-text">
							<h4><?php echo $edificio ?></h4>

							<div class="card-image"><img class="responsive-img" src="<?php echo $this->baseUrl('image/edifici/'.$edificio.'.jpg'); ?>"> </div>
							<table class="bordered">

								<tbody>
								<tr>
									<td>Piano:</td>
									<td><?php echo $numPiano;?></td>

								</tr>
								<tr>
									<td>Stanza:</td>
									<td><?php echo $stanza;?></td>
								</tr>

								</tbody>
							</table>

						</div>
					</div>
				</div>
			</div>
			<!-- parte destra -->
			<div id="dx" class="col s12 m8 l8">
				<div class="center">
					<img class="responsive-img" src="<?php echo $this->baseUrl('image/piante/'.$edificio.' Piano '.$numPiano.'.jpg'); ?>" >
				</div>
			</div>
		</div>

<!--tasto menu -->
<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red">
		<i class="large material-icons">add_circle</i>
	</a>
	<ul>

		<li><a class="btn-floating purple lighten-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Logout" href="<?php echo $this->url(
				array('controller' => 'index', 'action' => 'index'),null,true); ?>"><i class="material-icons">exit_to_app</i></a></li>



		<li><a class="btn-floating orange tooltipped" data-position="left" data-delay="50" data-tooltip="Modifica Dati" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'modificadatiutente'),null,true); ?>"><i class="material-icons">mode_edit</i></a></li>


		<li><a class="btn-floating tooltipped" data-position="left" data-delay="50" data-tooltip="Riposizionati" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'checkin'),null,true); ?>"><i class="material-icons">place</i></a></li>

		<li><a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Scappa" href="<?php echo $this->url(
				array('controller' => 'livello1', 'action' => 'visualizzafuga'),null,true); ?>"  ><i class="material-icons">directions</i></a></li>

		<li><a class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Segnala" href="<?php echo $this->url(
		array('controller' => 'livello1', 'action' => 'segnalazione'),null,true); ?>"><i class="material-icons">add_alert</i></a></li>

	</ul>
</div>
</body>
</html>