<html>
<head>

<body>
<div class="container">
	<div class="row center-align">
		<h1 class="green-text center-align">Modifica i tuoi dati</h1>
		<div class="row left-align">
			<?php echo $this->modificaform; ?>
		</div>

	</div>
</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Indietro" href="<?php echo $this->url(
		array('controller' => 'livello1', 'action' => 'index')) ?>">
		<i class="large material-icons">arrow_back </i>
	</a>
</div>
</body>
</head>
</html>