<html>
<head>

<body>
<div id="view-content">

	<div class="container">
		<div class="row center-align">
			<h1 class="green-text center-align">Modifica i tuoi dati</h1>
			<div class="card grey lighten-5">
				<div class="card-content">
					<div class="container">
						<?php echo $this->modificaform; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="fixed-action-btn click-to-toggle vertical" style="bottom: 45px; right: 24px;">
	<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Torna alla Home" href="<?php echo $this->url(
		array('controller' => 'livello1', 'action' => 'index')) ?>">
		<i class="large material-icons">home</i>
	</a>
</div>
</body>
</head>
</html>