<html>
	<head>
		<div>
			<?php
			$pianta=$this->pianta;
			?>
		</div>
		<body>
			<div class="container">
				<div class="row center-align">
					<h1 class="green-text center-align">Piano di Fuga</h1>
					<div class="row">
						<img class="responsive-img" src="<?php echo $this->baseUrl('image/piante/piani di fuga/'.$pianta.'.jpg'); ?>">
					</div>
				</div>
			</div>
		</body>
	</head>
</html>