<html>
	<head>
		<div>
			<?php
			$pianta=$this->pianta;
			?>
		</div>
		<body>
			<div class="container">
				<div class="row center-align">
					<h1 class="green-text center-align">Piano di Fuga</h1>
					<div class="row">
						<img class="responsive-img" src="<?php echo $this->baseUrl('image/piante/piani di fuga/'.$pianta.'.jpg'); ?>">
					</div>
				</div>
			</div>

			<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
				<a class="btn-floating btn-large red tooltipped" data-delay="50" data-position="left" data-tooltip="Indietro" href="<?php echo $this->url(
					array('controller' => 'livello1', 'action' => 'index'),null,true); ?>">
					<i class="large material-icons">replay</i>
				</a>
			</div>
		</body>
	</head>
</html>