<!DOCTYPE html>

<html lang="it" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <!-- cambia il colore della navbar nei dispositivi mobili -->
    <meta name="theme-color" content="#4caf50" />

    <title>Safer Place</title>

    <!-- SETUP -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <!-- CONFIGURAZIONE DI MATERIALIZE -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/materialize.min.css'); ?>">
    <!--<script src="<?php echo $this->baseUrl('js/materialize.min.js'); ?>"></script>-->
    <!--<script type="text/javascript" src="<?php echo $this->baseUrl('js/materialize.min.js');?>"></script>-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- favicon -->
    <link rel="icon"
          type="image/png"
          href="<?php echo $this->baseUrl('image/logostilpiccolo.png');?>">

    <!-- script per attivare i popup con jquery -->
    <!--<script type="text/javascript" src="<?php echo $this->baseUrl('js/modaljs.js');?>"></script>-->

    <!--  Scripts-->
    <script  src="<?php echo $this->baseUrl('js/jquery.min.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/materialize.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/index.js');?>"></script>

</head>

<body>
<!-- NAV BAR -->
<div class="navbar-fixed">


    <nav class="green  white-text">
        <div class="nav-wrapper container">
            <a href="index" class="brand-logo" id="containerLogo" style="margin-top: 12px"><img src="<?php echo $this->baseUrl('image/logoM.png');?>" height="41.1"></a>

            <ul class="right hide-on-med-and-down">
                <li>
                    <div class="chip green darken-2 white-text">
                        <img src="<?php echo $this->baseUrl('image/profili/NicolaSabino_94.jpg');?>" alt="Contact Person">NicolaSabino_94
                    </div>
                </li>
                <li><a class="" href="#login">Impostazioni</a></li>
                <li><a class="" href="#info">Logout</a></li>

            </ul>
        </div>
    </nav>

</div>

<?php echo $this->layout()->content; ?>




</body>
</html>