<!DOCTYPE html>

<html lang="it">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <!-- cambia il colore della navbar nei dispositivi mobili -->
    <meta name="theme-color" content="#4caf50" />

    <title>Safer Place</title>

    <!-- SETUP -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <!-- CONFIGURAZIONE DI MATERIALIZE -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/materialize.min.css'); ?>">
    <script src="<?php echo $this->baseUrl('js/materialize.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/materialize.min.js');?>"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- favicon -->
    <link rel="icon"
          type="imag/png"
          href="<?php echo $this->baseUrl('image/logostilpiccolo.png');?>">

    <!-- script per attivare i popup con jquery -->
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/modaljs.js');?>"></script>

    <!--  Scripts-->
    <script  src="<?php echo $this->baseUrl('js/jquery.min.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/materialize.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/index.js');?>"></script>

</head>

<body>
<!-- NAV BAR -->
<div class="navbar-fixed">


    <nav class="green  white-text">
        <div class="nav-wrapper container">
            <a href="index" class="brand-logo" id="containerLogo" style="margin-top: 12px"><img src="<?php echo $this->baseUrl('image/logoM.png');?>" height="41.1" ></a>
        </div>

    </nav>
</div>
<?php echo $this->layout()->content; ?>

<!-- Pulsante azioni -->
<div class="fixed-action-btn" >
    <a class="btn-floating btn-large red">
        <i class="large material-icons">menu</i>
    </a>
    <ul>
        <li><a class="btn-floating purple tooltipped" data-tooltip="Logout" data-delay="50" data-position="left"
               href="<?php echo $this->url(array(
                       'controller' => 'index',
                       'action'     => 'index'
                   )). '"
            >';?>

                <i class="material-icons">exit_to_app</i>
            </a>
        </li>
        <li>
            <a class="btn-floating blue tooltipped" data-delay="50" data-position="left"
               data-tooltip="Dashboard" href="<? echo $this->url(array(
                'controller' => 'livello2',
                'action'     => 'dashboard'));?>">
                <i class="material-icons">home</i>
            </a>
        </li>
        <li>
            <a class="btn-floating yellow darken-1 tooltipped" data-delay="50" data-position="left"
               data-tooltip="Avvia evacuazione" href="<? echo $this->url(array(
                                                                        'controller' => 'livello2',
                                                                        'action'     => 'evacuazione'));?>
            " >
                <i class="material-icons">warning</i>
            </a>
        </li>
        <li><a class="btn-floating green tooltipped" data-tooltip="Impostazioni" data-delay="50" data-position="left"
                href="<?php echo $this->url(array(
                                            'controller' => 'livello2',
                                            'action'     => 'modifica'
                                            )). '"
            >';?>

                <i class="material-icons">build</i></a>
            </a>
        </li>

    </ul>
</div>
</body>
</html>
