<!DOCTYPE html>

<html lang="it">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <!-- cambia il colore della navbar nei dispositivi mobili -->
    <meta name="theme-color" content="#4caf50" />

    <title>Safer Place</title>

    <!-- SETUP -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <!-- CONFIGURAZIONE DI MATERIALIZE -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/materialize.min.css'); ?>">
    <script src="<?php echo $this->baseUrl('js/materialize.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/materialize.min.js');?>"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- favicon -->
    <link rel="icon"
          type="imag/png"
          href="<?php echo $this->baseUrl('image/logostilpiccolo.png');?>">

    <!-- script per attivare i popup con jquery -->
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/modaljs.js');?>"></script>

    <!--  Scripts-->
    <script  src="<?php echo $this->baseUrl('js/jquery.min.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/materialize.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/index.js');?>"></script>

</head>

<body>
<!-- NAV BAR -->
<div class="navbar-fixed">


    <nav class="green  white-text">
        <div class="nav-wrapper container">
            <a href="index" class="brand-logo" id="containerLogo" style="margin-top: 12px"><img src="<?php echo $this->baseUrl('image/logoM.png');?>" height="41.1" ></a>
        </div>

    </nav>
</div>

<!-- menu ausiliario per l'admin -->
<!--<div class="navbar-fixed">
    <nav class ="white">


        <div class="row">
            <div class="col s12">
                <ul class="tabs">
                    <li class="tab col s3 spinner-green"><a class="active green-text" href="<?php echo $this->url(
                            array(
                                'controller' => 'livello3',
                                'action' => 'gestioneedifici'
                            )
                        );  ?>" style="margin-left: -40px"><i class="material-icons left" style="margin-top: -10px; margin-left: 40px"><img src="<?php echo $this->baseUrl('image/icone/gestioneedificiiconv.png');?>" style="height: 24px; width: 24px"></i>Gestione edifici</a></li>
                    <li class="tab col s3 "><a class="green-text" href="<?php echo $this->url(
                            array(
                                'controller' => 'livello3',
                                'action' => 'gestionepianifuga'
                            )
                        );  ?>" style=" margin-left: -40px"><i class="material-icons left" style="margin-top: -10px; margin-left: 40px"><img src="<?php echo $this->baseUrl('image/icone/gestionepianifugaiconv.png');?>" style="height: 24px; width: 24px"></i>Gestione Piani di Fuga</a></li>
                    <li class="tab col s3 "><a class="green-text" href="#gestUtenti" style=" margin-left: -40px"><i class="material-icons left" style="margin-top: -10px; margin-left: 40px"><img src="<?php echo $this->baseUrl('image/icone/gestioneutentiiconv.png');?>" style="height: 24px; width: 24px"></i>Gestione Utenti</a></li>
                    <li class="tab col s3 "><a class="green-text" href="#gestFAQ" style=" margin-left: -40px"><i class="material-icons left" style="margin-top: -10px; margin-left: 40px"><img src="<?php echo $this->baseUrl('image/icone/gestioneFAQiconv.png');?>" style="height: 24px; width: 24px"></i>Gestione FAQ</a></li>
                </ul>
            </div>

    </nav>-->

<div class="fixed-action-btn vertical click-to-toggle" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red" href="#">
        <i class="material-icons">menu</i>
    </a>
    <ul>
        <li>
            <a class="btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Edifici" href="<?php echo $this->url(
                array(
                    'controller' => 'livello3',
                    'action' => 'gestioneedifici'
                )
            );  ?>">
                <i class="material-icons">business</i>
            </a>
        </li>
        <li>
            <a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Piani di Fuga" href="<?php echo $this->url(
                array(
                    'controller' => 'livello3',
                    'action' => 'gestionepianifuga'
                )
            );  ?>">
                <i class="material-icons">trending_up</i>
            </a>
        </li>
        <li>
            <a class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Utenti" href="<?php echo $this->url(
                array(
                    'controller' => 'livello3',
                    'action' => 'gestioneutenti'
                )
            );  ?>">
                <i class="material-icons">person</i>
            </a>
        </li>
        <li>
            <a class="btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="Gestisci Faq" href="<?php echo $this->url(
                array(
                    'controller' => 'livello3',
                    'action' => 'gestionefaq'
                )
            );  ?>">
                <i class="material-icons">live_help</i>
            </a>
        </li>
    </ul>

</div>

</div>
<?php echo $this->layout()->content; ?>
</body>
</html>
