<!DOCTYPE html>

<html lang="it">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <!-- cambia il colore della navbar nei dispositivi mobili -->
    <meta name="theme-color" content="#4caf50" />

    <title>Safer Place</title>

    <!-- SETUP -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <!-- CONFIGURAZIONE DI MATERIALIZE -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/materialize.min.css'); ?>">
    <script src="<?php echo $this->baseUrl('js/materialize.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/materialize.min.js');?>"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- favicon -->
    <link rel="icon"
          type="imag/png"
          href="<?php echo $this->baseUrl('image/logostilpiccolo.png');?>">

    <!-- script per attivare i popup con jquery -->
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/modaljs.js');?>"></script>

    <!--  Scripts-->
    <script  src="<?php echo $this->baseUrl('js/jquery.min.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/materialize.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/index.js');?>"></script>

</head>

<body>
<!-- NAV BAR -->
<div class="navbar-fixed">


    <nav class="green  white-text">
        <div class="nav-wrapper container">
            <a href="index" class="brand-logo" id="containerLogo" style="margin-top: 12px"><img src="<?php echo $this->baseUrl('image/logoM.png');?>" height="41.1" ></a>
        </div>

    </nav>
</div>

<!-- navbar ausiliaria per l'Admin -->
<div class="navbar-fixed">
    <nav class ="white">

        <!-- Tabs -->
        <div class="row">
            <div class="col s12">
                <ul class="tabs">
                    <li class="tab col s3 spinner-green"><a class="active green-text" href="#gestEdifici" style="margin-left: -40px"><i class="material-icons left" style="margin-top: -10px; margin-left: 40px"><img src="image/icone/gestioneedificiiconv.png" style="height: 24px; width: 24px"></i>Gestione edifici</a></li>
                    <li class="tab col s3 "><a class="green-text" href="#gestPdf" style=" margin-left: -40px"><i class="material-icons left" style="margin-top: -10px; margin-left: 40px"><img src="image/icone/gestionepianifugaiconv.png" style="height: 24px; width: 24px"></i>Gestione Piani di Fuga</a></li>
                    <li class="tab col s3 "><a class="green-text" href="#gestUtenti" style=" margin-left: -40px"><i class="material-icons left" style="margin-top: -10px; margin-left: 40px"><img src="image/icone/gestioneutentiiconv.png" style="height: 24px; width: 24px"></i>Gestione Utenti</a></li>
                    <li class="tab col s3 "><a class="green-text" href="#gestFAQ" style=" margin-left: -40px"><i class="material-icons left" style="margin-top: -10px; margin-left: 40px"><img src="image/icone/gestioneFAQiconv.png" style="height: 24px; width: 24px"></i>Gestione FAQ</a></li>
                </ul>
            </div>

    </nav>

</div>
<?php echo $this->layout()->content; ?>
</body>
</html>
