<!DOCTYPE html>

<html lang="it">
<head>

    <!-- configurazioni da bootstrap -->
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headScript(); ?>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" media="screen" rel="stylesheet" type="text/css" >
    <!-- favicon -->
    <link rel="icon"
          type="imag/png"
          href="<?php echo $this->baseUrl('image/logostilpiccolo.png');?>">


    <!-- Carico gli script e configuro materialize-->
    <script  src="<?php echo $this->baseUrl('js/jquery.min.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/materialize.js');?>"></script>
    <script  src="<?php echo $this->baseUrl('js/index.js');?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/modaljs.js');?>"></script>

    <!-- metatag materialize -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta name="theme-color" content="#4caf50" />


</head>

<body>


<ul id="menu" class="dropdown-content">
    <li><a href="<?php echo $this->url(
            array('controller' => 'livello2', 'action' => 'modificadatiutente'),null,true); ?>">Modifica Profilo</a></li>
    <li><a href="<?php echo $this->url(
            array('controller' => 'index', 'action' => 'logout'),null,true); ?>">Logout</a></li>
</ul>

<!-- NAV BAR -->
<div class="navbar-fixed">


    <nav class="green  white-text">
        <div class="nav-wrapper container">
            <a href="<?php echo $this->url(
                array(
                    'controller' => 'livello2',
                    'action'=>'index',
                )
            ); ?>" class="brand-logo" id="containerLogo" style="margin-top: 12px"><img src="<?php echo $this->baseUrl('image/logoM.png');?>" height="41.1"></a>

            <ul class="right">
                <li>
                    <a class="dropdown-button" data-beloworigin="true" href="#" data-activates="menu"><div class="chip green lighten-3">
                            <img src="<?php echo $this->baseUrl('image/icone/account.png');?>" alt="Contact Person">
                            <?php
                            echo $this->authInfo('username');
                            ?>
                        </div><i class="material-icons right">arrow_drop_down</i></a>
                </li>
            </ul>
        </div>
    </nav>

</div>
<?php echo $this->layout()->content; ?>

<!-- Pulsante azioni -->
<div class="fixed-action-btn" >
    <a class="btn-floating btn-large red">
        <i class="large material-icons">menu</i>
    </a>
    <ul>
        <li>
            <a class="btn-floating orange tooltipped" data-position="left" data-delay="50" data-tooltip="FAQ" href="<?php echo $this->url(
                array('controller' => 'index', 'action' => 'faq'),null,true); ?>">
                <i class="material-icons">live_help</i>
            </a>
        </li>
        <li>
            <a class="btn-floating blue tooltipped" data-delay="50" data-position="left"
               data-tooltip="Dashboard" href="<?php echo $this->url(array(
                'controller' => 'livello2',
                'action'     => 'dashboard'));?>">
                <i class="material-icons">home</i>
            </a>
        </li>
        <li>
            <a class="btn-floating yellow darken-1 tooltipped" data-delay="50" data-position="left"
               data-tooltip="Avvia evacuazione" href="<?php echo $this->url(array(
                                                                        'controller' => 'livello2',
                                                                        'action'     => 'evacuazione'), null, true);?>
            " >
                <i class="material-icons">warning</i>
            </a>
        </li>
        

    </ul>
</div>
</body>
</html>
